"""
Memory — simple shared state for the agent.

This module holds the agent's working memory across the planning and
execution phases. It tracks:
    - The original goal
    - The plan generated by the Planner
    - Results of each executed step
    - Artifacts produced (file paths)
    - A chronological decision log

Design note: we keep this in-memory for the MVP. Swapping to Redis or a
vector store later is a one-class change.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from pydantic import BaseModel, Field


class StepResult(BaseModel):
    """Outcome of a single executed step."""
    step_id: int
    status: str  # "success" | "error" | "skipped"
    tool_used: Optional[str] = None
    output: Optional[Any] = None
    error: Optional[str] = None
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())


class LogEntry(BaseModel):
    """A single entry in the agent's decision log."""
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    phase: str  # "planner" | "executor" | "system"
    message: str
    data: Optional[dict] = None


class AgentMemory:
    """Shared working memory for one agent run."""

    def __init__(self, goal: str):
        self.goal: str = goal
        self.plan: Optional[dict] = None
        self.results: list[StepResult] = []
        self.artifacts: dict[str, str] = {}  # human-readable name -> file path
        self.log: list[LogEntry] = []

    # -- mutation -------------------------------------------------------------

    def set_plan(self, plan: dict) -> None:
        self.plan = plan
        self.add_log("planner", "Plan generated", data=plan)

    def add_result(self, result: StepResult) -> None:
        self.results.append(result)
        self.add_log(
            phase="executor",
            message=f"Step {result.step_id} -> {result.status}",
            data=result.model_dump(),
        )

    def add_artifact(self, name: str, path: str) -> None:
        self.artifacts[name] = path
        self.add_log("executor", f"Artifact registered: {name} -> {path}")

    def add_log(self, phase: str, message: str, data: Optional[dict] = None) -> None:
        self.log.append(LogEntry(phase=phase, message=message, data=data))

    # -- read -----------------------------------------------------------------

    def context_summary(self, max_chars: int = 1500) -> str:
        """
        Compact text snapshot of memory, designed to be injected into prompts.
        Keeps the most recent step results in priority and truncates aggressively.
        """
        lines = [f"Goal: {self.goal}"]

        if self.plan:
            lines.append(f"Plan has {len(self.plan.get('steps', []))} steps.")

        if self.results:
            lines.append("Previous step results:")
            for r in self.results:
                preview = (str(r.output)[:160] if r.output else r.error or "").replace("\n", " ")
                lines.append(
                    f"  - Step {r.step_id} [{r.status}] via {r.tool_used}: {preview}"
                )

        if self.artifacts:
            lines.append("Artifacts produced so far:")
            for name, path in self.artifacts.items():
                lines.append(f"  - {name}: {path}")

        text = "\n".join(lines)
        if len(text) > max_chars:
            text = text[:max_chars] + "\n... [context truncated]"
        return text

    # -- persistence ----------------------------------------------------------

    def save_to_json(self, path: str) -> None:
        """Persist the full memory to disk for auditing / debugging."""
        data = {
            "goal": self.goal,
            "plan": self.plan,
            "results": [r.model_dump() for r in self.results],
            "artifacts": self.artifacts,
            "log": [entry.model_dump() for entry in self.log],
        }
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    def load_from_json(self, path: str) -> None:
        """Load memory from disk to resume interrupted sessions."""
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        # Reconstruct memory state from JSON data
        self.goal = data["goal"]
        self.plan = data["plan"]
        self.results = [StepResult(**r) for r in data["results"]]
        self.artifacts = data["artifacts"]
        self.log = [LogEntry(**entry) for entry in data["log"]]
