"""
Planner — turns a high-level goal into a structured, ordered plan.

We use LangChain's `with_structured_output` so the LLM emits a Pydantic-
validated object instead of free-form text. This makes the executor's job
trivial and removes a whole class of parsing bugs.
"""

from pydantic import BaseModel, Field
from typing import Dict, Any, List
from langchain_core.language_models.chat_models import BaseChatModel

from prompts.prompts import build_planner_prompt


class PlanStep(BaseModel):
    """A single executable step in the agent's plan."""
    id: int = Field(description="1-based sequential id of this step.")
    description: str = Field(description="What this step does, in plain language.")
    suggested_tool: str = Field(description="Name of the tool that should run this step.")
    expected_output: str = Field(description="What this step should produce.")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the tool.")
    reasoning: str = Field(default="", description="Why this step is necessary.")
    dependencies: List[int] = Field(default_factory=list, description="Step IDs that must complete first.")


class Plan(BaseModel):
    """The full plan generated by the planner."""
    goal: str = Field(description="The original user goal, restated.")
    reasoning: str = Field(description="Brief explanation of why this plan satisfies the goal.")
    estimated_time: int = Field(default=300, description="Estimated total execution time in seconds.")
    confidence: float = Field(default=0.8, description="Confidence score for this plan (0.0-1.0).")
    steps: List[PlanStep] = Field(description="Ordered list of steps to execute.")


class Planner:
    """LLM-powered planner that decomposes goals into ordered tool calls."""

    def __init__(self, llm: BaseChatModel, tools_catalog: str):
        """
        Args:
            llm: A LangChain chat model. Inject a low-temperature instance
                 (see `get_planner_llm`) for consistent plans.
            tools_catalog: Human-readable catalog of available tools (name + desc).
                           Injected verbatim into the planner system prompt.
        """
        self.llm = llm
        self.tools_catalog = tools_catalog
        self.prompt = build_planner_prompt()

    def plan(self, goal: str) -> Plan:
        """
        Generate a plan for the given goal.

        Returns:
            A validated `Plan` instance.

        Raises:
            ValueError: if the LLM returns something that cannot be validated.
        """
        structured_llm = self.llm.with_structured_output(Plan)
        chain = self.prompt | structured_llm
        result = chain.invoke(
            {"goal": goal, "tools_catalog": self.tools_catalog}
        )
        # Some providers return a dict instead of a Pydantic model — normalize.
        if isinstance(result, dict):
            result = Plan(**result)
        if not result.steps:
            raise ValueError("Planner returned a plan with zero steps.")
        return result


# Compatibility alias for existing code
AgentPlanner = Planner
