"""
Report tool — assembles the final Markdown deliverable.

The LLM passes the narrative content (executive summary, insights,
recommendations) as structured arguments. We handle the formatting,
chart embedding, and file writing here, so the prompt stays small
and the output is consistent.
"""

from datetime import datetime
from pathlib import Path
from typing import Optional

from langchain_core.tools import tool
from pydantic import BaseModel, Field


OUTPUTS_DIR = Path("outputs")


class ReportArgs(BaseModel):
    title: str = Field(description="Title of the report.")
    executive_summary: str = Field(
        description="2-4 sentence high-level summary for non-technical readers."
    )
    insights: list[str] = Field(
        description="Bullet list of concrete, data-backed findings."
    )
    recommendations: list[str] = Field(
        description="Bullet list of actionable next steps based on the insights."
    )
    chart_paths: Optional[list[str]] = Field(
        default=None,
        description="Optional list of chart image paths to embed in the report.",
    )
    filename: str = Field(
        default="report.md",
        description="Output filename inside outputs/.",
    )


@tool("write_report", args_schema=ReportArgs)
def write_report(
    title: str,
    executive_summary: str,
    insights: list[str],
    recommendations: list[str],
    chart_paths: Optional[list[str]] = None,
    filename: str = "report.md",
) -> dict:
    """Write the final Markdown report to outputs/ and return its path.

    This is the LAST tool the agent calls. Its arguments ARE the
    deliverable, so prompt the model to fill them with care.
    """
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUTPUTS_DIR / filename

    parts: list[str] = []
    parts.append(f"# {title}\n")
    parts.append(
        f"_Generated by AI Operations Agent on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}_\n"
    )

    parts.append("## 📌 Executive Summary\n")
    parts.append(executive_summary.strip() + "\n")

    parts.append("## 🔍 Key Insights\n")
    for item in insights:
        parts.append(f"- {item.strip()}")
    parts.append("")

    parts.append("## ✅ Recommendations\n")
    for item in recommendations:
        parts.append(f"- {item.strip()}")
    parts.append("")

    if chart_paths:
        parts.append("## 📊 Visualizations\n")
        for path in chart_paths:
            # Use a path relative to the report file so it renders in any viewer.
            rel = Path(path)
            try:
                rel = rel.relative_to(OUTPUTS_DIR)
            except ValueError:
                pass  # absolute or external path — leave as is
            parts.append(f"![{rel.stem}]({rel.as_posix()})\n")

    parts.append("---\n")
    parts.append("_This report was generated autonomously. Always validate "
                 "critical decisions with a human expert._\n")

    out_path.write_text("\n".join(parts), encoding="utf-8")
    return {
        "report_path": str(out_path),
        "char_count": sum(len(p) for p in parts),
    }
